# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rgW-wECZfhPPoM8SXKkZFAs9itO5XtVA
"""

scores = list(map(int, input().split()))
count = sum(1 for s in scores if s < 60)
print(count)

nums = list(map(int, input().split()))

print(max(nums))
print(min(nums))
if scores:
    average = sum(scores) / len(scores)
    print(average)
